# Generated by Django 2.2.2 on 2019-06-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.TextField()),
                ('movie_series', models.TextField(blank=True, null=True)),
                ('actor', models.TextField(blank=True, null=True)),
                ('actress', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False)),
                ('theater', models.TextField()),
                ('city', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Theater',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, null=True)),
                ('starttime', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TimeTable',
                'managed': False,
            },
        ),
    ]
